### PR TITLE
add bicep version of recommended_alerts_ARM

### PR DESCRIPTION
**Pull request by carlin-q-scott**
Continuation of #921 using the ci_prod branch as the base

### CODE REVIEW

**Comment by carlin-q-scott** [comment]
@ganga1980 can you look at this PR please?

**Comment by ganga1980** [comment]
> @ganga1980 can you look at this PR please?

> @carlin-q-scott - We are in the process of deprecating the recommended alerts which are based off custom metrics.  Can you please consider using Prometheus rules based alerts - https://azure.microsoft.com/en-us/updates/container-insights-recommended-alerts-custom-metrics-preview-will-be-retired-on-14-march-2026/ ?

**Comment by carlin-q-scott** [comment]
@ganga1980 I responded to that in the other PR thread here: https://github.com/microsoft/Docker-Provider/pull/921#issuecomment-1489038156

**Comment by ganga1980** [comment]
> @ganga1980 I responded to that in the other PR thread here: [#921 (comment)](https://github.com/microsoft/Docker-Provider/pull/921#issuecomment-1489038156)

> @carlin-q-scott  - Thanks for the response. Our recommendation to use Prometheus metrics based recommended alerts.  Here are the Bicep templates for the same - https://github.com/Azure/prometheus-collector/tree/main/AddonBicepTemplate. Regarding the gaps, please reach out  @Sohamdg081992 and @vdiec . If you still want to continue to use metrics rules based in recommended alerts until you plan to migrate, please let me know and I can approve this PR to get merged.

**Pull request closed without merging**
